a_site/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='a_site'

urlpatterns=[
	path('',views.index,name='index'),
	path('validate/',views.validate,name='validate'),
	path('insert/',views.insert,name='insert'),
	path('wishes/',views.wishes,name='wishes'),
	
] + static(settings.STATIC_URL,decument_root=settings.STATIC_ROOT)

anonymoussite/urls.py
from django.conf.urls import  include, url
from django.contrib import admin
from django.urls import path,include

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('<slug:uname>/',include('a_site.urls')),
]

a_site/models.py
from django.db import models

# Create your models here.


class Wishes(models.Model):
	name = models.CharField(max_length=50)
	w_text = models.CharField(max_length=1000)	
	idate = models.DateTimeField('insertedtime')
	def __str__(self):
		return self.w_text

class Questions(models.Model):
	question=models.CharField(max_length=50)

class Answer(models.CharField):
	ans = models.CharField(max_length=200)
	qn = models.ForeignKey('Question',on_delete=models.DO_NOTHING,default="")

a_site/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect

from django.urls import reverse

from .models import Wishes

from django.utils import timezone

def index(request,uname):
	uname="Afridy"
		
	return render(request,'a_site/index1.html',{'uname':uname})

def insert(request,uname):
	return render(request,'a_site/insert.html',{'uname':uname})

def wishes(request,uname):
	w = Wishes.objects.all().order_by('idate').reverse()
	return render(request,'a_site/wishes.html',{'wishes':w,'uname':uname})

def validate(request,uname):
	wish = request.POST['wish']
	name = request.POST['wname'] 
	new = Wishes(name=name, w_text = wish,idate=timezone.now())
	new.save()
	return HttpResponseRedirect(reverse('a_site:wishes',args=[uname]))

def question(request,uname):
	return render(request,'a_site/question.html',{'uname':uname})

a_site/templates/a_site/index.html
<h1>Anomymous Site</h1>

<h2>Insert a Wish</h2>
	
<form action="{% url 'a_site:validate' %}" method="post">
{% csrf_token %}

	<input type="text" name="wish"><br><br>
	<input type="submit" value="submit">
</form>
<h2>Wishes</h2>

a_site/templates/a_site/index1.html
{% extends 'a_site/nav.html' %}

{% block content %}
	<title>HBD Afridy</title>
	<div class="home-center">
	<div id="f-heading" class="text-center">
			<span class="happy">Happy</span>       <span class="birthday">Birthday</span>
	</div>
	
	<div class="container-fluid text-center" id="hbd">
			Afridy 
	</div>
	</div>
	
	
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% endblock content %}
	 

a_site/templates/a_site/insert.html
{% extends 	'a_site/nav.html' %}

{% block content %}



<title>wish afridy</title>
<head lang="en">
	
	<div id="w-heading" class="text-center">
		Send Birthday wishes to Afridy
	</div>
	
	<form action="{% url 'a_site:validate' uname %}" method="post">
	{% csrf_token %}
	  <div class="form-group container">
	  <div class="input-c">
	    <span class="form-top ">Type your wishes</span>
	  
	  <textarea type="text" class="form-control" aria-label="With textarea" name="wish" maxlength="1000" placeholder="send your wishes to  Afridy"></textarea>
	</div>
	<div class="input-c">
	    <span class="form-top" ">wishes from</span>
	  
	  <input type="text" class="form-control" aria-label="With textarea" name="wname" value="anonymous" maxlength="50"></input>
	</div>
	<button type="submit" class="btn btn-default btn-primary input-b">Submit</button>
	</div>
	</form>


	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% endblock  %}

a_site/templates/a_site/nav.html
<head lang="en">
	<title>anonymous wishes</title>
	<meta charset="utf-8">	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css'  %}">
	<link href='https://fonts.googleapis.com/css?family=Caesar Dressing' rel='stylesheet'>
	<link href='https://fonts.googleapis.com/css?family=Carter One' rel='stylesheet'>	
	
	<link href='https://fonts.googleapis.com/css?family=Andika' rel='stylesheet'>
	<link href='https://fonts.googleapis.com/css?family=Carter One' rel='stylesheet'>


	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css'  %}">
</head>

<body >
	<nav id="navbar-example2" class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a id ="logo" class="navbar-brand" href="{% url 'a_site:index' uname %}">ANOMYMOUS WISHES</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'a_site:index' uname %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'a_site:insert' uname %}">Wish Afridy </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'a_site:wishes' uname %}">wishes </a>
      </li>
      

    </ul>
  </div>
</nav>

{% block content %}

{% endblock  %}


<div id="footer" class="container-fluid text-center fixed-bottom ">
		&copy   kolantha paiyan     2020-2021
</div>

a_site/templates/a_site/wishes.html
{% extends 	'a_site/nav.html' %}

{% block content %}


<title>All wishes</title>

	<div id="f-heading" class="text-center">
		Wishes
	</div>


	<!--<div class="container primary">
		<h1>Wishes</h1>
		
	</div>
	-->
	<div id="scroll" class="container rouned">
		{% for  w in wishes.all %}
		<div class="w-box rounded">
		<h3 class="wish-text">{{w.w_text}}</h3><h5 id="name">by <span id="wisher">{{w.name}}</span></h5>
		</div>
		{% endfor %}
	</div>
	
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock content %}